application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /client
  static_dir: client
  login: required
- url: /bower_components
  static_dir: bower_components
- url: /.*
  script: hello.app
